name: Built & Release with Ubuntu
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add Toolchain PPA
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      - name: Add debian repository
        uses: myci-actions/add-deb-repo@10
        with:
          repo: deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main
          repo-name: llvm-toolchain
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
          update: true
          install: clang-13 llvm-13
      - name: Python 3.9 Time
        uses: actions/setup-python@v3.1.2
        with:
          python-version: '3.9'
      - name: Install requirements
        run: |
          python3.9 -m pip install tatsu requests
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update version file
        run: |
          echo -n VERSION= > version
          git tag --points-at HEAD | tac | grep -Pxom1 "v([0-9]+\.[0-9]+\.[0-9]+)(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+)?" | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+" | tr -d "\n" >> version
      - name: Build release
        run: |
          python3.9 ./build.py release
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: princess*.tar.gz
      - name: Commit release
        run: |
          git add version
          git commit --message=Version bump from tag.
          git push
